load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "ThemeManager",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//libraries/ColorsUI:ColorsUI",
        "//libraries/FontsUI:FontsUI",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    info_plist_substitutions = info_plist_substitutions("ThemeManagerTests")
)