load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "EsoftUIKit",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        ":EsoftUIKitMedia",
        "//libraries/Atlas:Atlas",
        "//libraries/ThemeManager:ThemeManager",
        "//libraries/AutoLayoutKit:AutoLayoutKit",
        "//libraries/BaseUI:BaseUI",
        "//libraries/BaseFRP:BaseFRP",
        "//libraries/ShimmerUI:ShimmerUI",
        "//libraries/AnimateUI:AnimateUI",
        "//third-party/Pods:Yoga",
        "//third-party/Pods:YogaKit",
        "//third-party/Pods:IGListKit",
        "//third-party/Pods:IGListDiffKit",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    additional_linker_flags = [
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "/usr/lib/swift",
        "-Xlinker",
        "-rpath",
        "-Xlinker",
        "@executable_path/../../Frameworks",
    ],
    test_deps = [],
    info_plist_substitutions = info_plist_substitutions("EsoftUIKitTests")
)

apple_asset_catalog(
    name = "EsoftUIKitMedia",
    visibility = ["PUBLIC"],
    dirs = ["Resources/Media.xcassets"],
)
