load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "SpecialistsUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//third-party/Pods:Yoga",
        "//third-party/Pods:YogaKit",
        "//third-party/Pods:IGListKit",
        "//third-party/Pods:IGListDiffKit",
        "//libraries/EsoftUIKit:EsoftUIKit",
        "//libraries/CDNImageLink:CDNImageLink",
        "//features/Specialists/SpecialistsCore:SpecialistsCore",
        "//features/Specialists/SpecialistsImplementation:SpecialistsImplementation"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
    test_deps = [],
    info_plist_substitutions = info_plist_substitutions("SpecialistsTests")
)
