load("//config:utils.bzl",
    "library_configs",
)

load("//config:configs.bzl",
    "app_binary_configs",
    "info_plist_substitutions",
    "app_info_plist_substitutions",
    "DEVELOPMENT_LANGUAGE",
)

load("//config:buck_rule_macros.bzl",
    "framework_binary_dependencies",
    "framework_bundle_dependencies",
    "apple_test_lib",
    "apple_test_all",
)

additional_frameworks = []

framework_dependencies = []

static_libraries = [
    "//libraries/BaseUI:BaseUI",
    "//libraries/BaseFRP:BaseFRP",
    "//libraries/EsoftUIKit:EsoftUIKit",
    "//libraries/AutoLayoutKit:AutoLayoutKit",
    "//libraries/ThemeManager:ThemeManager",
    "//libraries/Logger:Logger",
    "//libraries/Network:Network",
    "//libraries/NetworkTrainee:NetworkTrainee",
    "//libraries/StateKit:StateKit",
    "//libraries/Currency:Currency",
    "//libraries/Localized:Localized",
    "//libraries/ListKit:ListKit",
    "//libraries/RxExtensions:RxExtensions",
    "//libraries/URLRequestKit:URLRequestKit",
    "//libraries/libphonenumber:libphonenumber",
    "//libraries/PhoneNumberFormat:PhoneNumberFormat",
    "//features/Specialists/SpecialistsCore:SpecialistsCore",
    "//features/Specialists/SpecialistsImplementation:SpecialistsImplementation",
    "//features/Specialists/SpecialistsUI:SpecialistsUI",
    "//integrations/TuitionIntegrations:TuitionIntegrations",
    "//libraries/CDNImageLink:CDNImageLink",
]

prebuilt_test_frameworks = [
    "//third-party/Pods:OHHTTPStubs"
]

prebuilt_frameworks = [
    "//third-party/Pods:Yoga",
    "//third-party/Pods:YogaKit",
    "//third-party/Pods:DBDebugToolkit",
    "//third-party/Pods:PINCache",
    "//third-party/Pods:PINRemoteImage",
    "//third-party/Pods:FLAnimatedImage",
    "//third-party/Pods:RxSwift",
    "//third-party/Pods:RxCocoa",
    "//third-party/Pods:RxRelay",
    "//third-party/Pods:IGListKit",
    "//third-party/Pods:IGListDiffKit",
    "//third-party/Pods:NeedleFoundation",
] + prebuilt_test_frameworks

resource_dependencies = [
    ":LaunchScreen",
    ":Icons",
    ":Localizations",
]

build_phase_scripts = [
    ":NeedleGenerated",
]

app_tests = [
    ":UnitTests",
    ":UnitTestsWithHostApp",
]

appTargetName = "TuitionApp"
appPath = "iphone-tuition"

apple_asset_catalog(
  name = "Icons",
  dirs = [
    "Resources/Assets.xcassets",
  ],
  app_icon = "AppIcon",
  visibility = ["PUBLIC"],
)

apple_resource(
    name = "LaunchScreen",
    files = [
        "Resources/Base.lproj/LaunchScreen.storyboard",
    ],
    visibility = ["PUBLIC"],
)

apple_resource(
    name = "Localizations",
    visibility = ["//apps/%s:"%appPath],
    files = [],
    variants = glob([
        "Resources/*.lproj/Localizable.strings",
    ]),
)

apple_library(
    name = "AppLibrary",
    visibility = [
        "//apps/%s:"%appPath,
        "//apps/%s/..."%appPath,
        "//apps/...",
    ],
    tests = app_tests,
    configs = library_configs(),
    swift_version = native.read_config("swift", "version"),
    srcs = glob([ "Sources/**/*.swift" ], exclude = [
        "Sources/Features/**/*.swift"
    ]),
    deps = [] + framework_binary_dependencies(framework_dependencies) + prebuilt_frameworks + static_libraries + build_phase_scripts,
    frameworks = additional_frameworks,
)

apple_binary(
    name = "AppBinary",
    visibility = [
        "//apps/%s:"%appPath,
        "//apps/%s/..."%appPath,
        "//apps/...",
    ],
    preprocessor_flags=[
        "-fobjc-arc",
        "-Wno-objc-designated-initializers",
    ],
    configs = app_binary_configs(appTargetName),
    swift_version = native.read_config("swift", "version"),
    srcs = [
        "BuckSupport/Empty.swift",
    ],
    deps = [
        ":AppLibrary",
    ]
    + resource_dependencies,
)

apple_bundle(
    name = appTargetName,
    visibility = [
        "//apps/%s:"%appPath,
    ],
    extension = "app",
    binary = ":AppBinary",
    product_name = appTargetName,
    info_plist = "Info.plist",
    info_plist_substitutions = app_info_plist_substitutions(appTargetName),
    deps = [
        "//third-party/Pods:PodsProjectGeneratorHack",
    ]
    + static_libraries
    + framework_bundle_dependencies(framework_dependencies)
    + prebuilt_frameworks,
)

apple_package(
    name = "AppPackage",
    bundle = ":%s" % appTargetName,
)

xcode_workspace_config(
    name = "workspace",
    workspace_name = "%s_Buck"% appTargetName,
    src_target = ":%s" % appTargetName,
)

apple_test_lib(
    name = "UnitTests",
    srcs = glob([
        "UnitTests/*.swift",
    ]),
    deps = [
        ":AppLibrary",
    ]
    + framework_bundle_dependencies(framework_dependencies)
    + prebuilt_frameworks,
    frameworks = [] + additional_frameworks,
    info_plist_substitutions = info_plist_substitutions("UnitTests")
)

apple_test_lib(
    name = "UnitTestsWithHostApp",
    run_test_separately = True,
    test_host_app = ":%s" % appTargetName,
    srcs = glob([
        "UnitTestsWithHostApp/*.swift",
    ]),
    deps = [
        ":AppLibrary",
    ],
    info_plist_substitutions = info_plist_substitutions("UnitTestsWithHostApp")
)

apple_test_all(
    name = "%sCITests"% appTargetName,
    libraries = [] + static_libraries,
    additional_tests = app_tests,
    prebuilt_frameworks = prebuilt_frameworks,
    info_plist_substitutions = app_info_plist_substitutions("%sCITests"% appTargetName),
)

xcode_prebuild_script(
    name = "NeedleGenerated",
    cmd = '"${SRCROOT}/../../tools/scripts/generate_di_graph.sh"',
    inputs = [],
    outputs = [],
    input_file_lists = [],
    output_file_lists = [],
)