load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "StorageKit",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//third-party/Pods:RxSwift",
        "//third-party/Pods:RxCocoa",
        "//third-party/Pods:RxRelay",
        "//third-party/Pods:Realm",
        "//third-party/Pods:RealmSwift",
        "//libraries/RealmKit:RealmKit",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
    test_deps = [],
    info_plist_substitutions = info_plist_substitutions("StorageKitTests")
)
