load("//Config:buck_rule_macros.bzl", "framework")

framework(
    name = "AutoLayoutKit",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)