load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "Network",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//libraries/Logger:Logger",
        "//third-party/Pods:RxSwift",
        "//third-party/Pods:RxCocoa",
        "//third-party/Pods:RxRelay"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/SystemConfiguration.framework",
    ],
    test_deps = [
        "//third-party/Pods:RxTest",
        "//third-party/Pods:OHHTTPStubs",
        "//third-party/Pods:RxBlocking"
    ],
    info_plist_substitutions = info_plist_substitutions("NetworkTests")
)
