load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "PhoneNumberFormat",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//libraries/libphonenumber:libphonenumber",
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
    ],
    info_plist_substitutions = info_plist_substitutions("PhoneNumberFormatTests")
)
