load("//config:buck_rule_macros.bzl", "static_library")
load("//config:configs.bzl", "info_plist_substitutions")

static_library(
    name = "NetworkDemo",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [
        "//third-party/Pods:RxSwift",
        "//third-party/Pods:RxCocoa",
        "//third-party/Pods:RxRelay"
    ],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/SystemConfiguration.framework",
    ],
    info_plist_substitutions = info_plist_substitutions("NetworkDemoTests")
)
