load("//config:buck_rule_macros.bzl", "static_library")

static_library(
    name = "ColorsUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    deps = [],
    frameworks = [
        "$SDKROOT/System/Library/Frameworks/Foundation.framework",
        "$SDKROOT/System/Library/Frameworks/UIKit.framework",
    ],
)